language: c

env:
  global:
    # GITHUB_TOKEN
    - secure: "G+UsY3jHUqUc2Snbl6WIFDcUyO4RxyiWCducqDZY/6ykwk0Y9mvOgY2qsfNQFSguzSo/ZE4D1SYL4DermDFwNtmOOC8CfIsgFegpoCTBDwwTKOiD0FjuUlOwbe44nTsDqy68Jgg63EbR+sjnS0joJNsJy2rVG9vrJm1cN65K624="

before_install:
  - curl -OL http://raw.github.com/luckyrandom/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - curl -OL http://raw.github.com/luckyrandom/r-travis/master/scripts/github-release.rb
  - chmod 755 ./github-release.rb
  - ./travis-tool.sh deploy ./rdummypackage*.tar.gz
