language: c

env:
  global:
    # GITHUB_TOKEN
    - secure: "bmXSPaVBvstehUjKmJX7TmdnSousSQXEIfCitHZBLMGiEpWU9i+KUd4eErZzK5Rcz5LdmKzoYeLqu2J7rPVbU+ncDdGrDv2C8J6ul42c+EsgZ86Naba8SDmLmqhR+2qguXabWXqoX/dhsfbB2/8PmUNJMY2Zdsb9KcT/TbnJlkw="

before_install:
  - curl -OL http://raw.github.com/luckyrandom/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh deploy ./rdummypackage*.tar.gz
